"""Constantes e tempos de espera da inclusão CADIN."""

import sys
from pathlib import Path


if getattr(sys, "frozen", False):
    PASTA_BASE = Path(sys.executable).resolve().parent
else:
    PASTA_BASE = Path(__file__).resolve().parent

PASTA_LOGS = PASTA_BASE / "logs"
PASTA_RESULTADOS = PASTA_BASE / "resultados"
PASTA_CHROME_PROFILE = PASTA_BASE / "chrome_profile"

URL_CADIN = "https://cadin.pgfn.gov.br/#/home"
CHROME_DEBUG_PORT = 9222
INTERVALO_RELOGIN_MINUTOS = 30
INTERVALO_RELOGIN_SEGUNDOS = INTERVALO_RELOGIN_MINUTOS * 60

TIMEOUT_PADRAO = 40
TIMEOUT_LOGIN_MANUAL = 900
TIMEOUT_CURTO = 8
TIMEOUT_GOVBR_APOS_CPF = 20
TIMEOUT_ESTABILIZAR_CAMPO_GOVBR = 8
TENTATIVAS_CONTINUAR_GOVBR = 3
TENTATIVAS_POR_ITEM = 2
PAUSA_APOS_CLIQUE_CAMPO = 0.12
PAUSA_ENTRE_CARACTERES = 0.005
PAUSA_ENTRE_CARACTERES_GOVBR = 0.035
PAUSA_APOS_ENTRAR_GOVBR = 2.0
PAUSA_ANTES_PREENCHER_GOVBR = 1.2
PAUSA_APOS_CPF_CNPJ = 1.0
TIMEOUT_NOME_APOS_CPF_CNPJ = 8
TIMEOUT_REFERENCIA_JA_INSCRITA = 1.5
PAUSA_APOS_INCLUIR = 0.5
PAUSA_APOS_LIMPAR = 0.2

COLUNAS_OBRIGATORIAS = [
    "CPF/CNPJ",
    "PROTOCOLO/PROCESSO",
    "AUTO DE INFRACAO",
    "DATA DE VENCIMENTO",
]

STATUS_SUCESSO = "SUCESSO"
STATUS_ERRO = "ERRO"
STATUS_IGNORADO = "IGNORADO"
STATUS_PARADO = "PARADO"
STATUS_TESTE = "TESTE"
STATUS_JA_INSCRITO = "JA_INSCRITO"

